buildscript {
    repositories {
        maven { url "https://plugins.gradle.org/m2/" }
        mavenCentral()
    }
    dependencies {
        classpath "gradle.plugin.com.matthewprenger:CurseGradle:1.4.0"
    }
}

plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.1.26'
}

apply plugin: "com.matthewprenger.cursegradle"

repositories {
    mavenCentral()
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
    maven {
        name = 'Mojang'
        url = 'https://libraries.minecraft.net/'
    }
}

def ver = System.getenv("APPVEYOR_BUILD_VERSION")
if(ver == null)
	ver = '0.0.0'

def key = System.getenv("CURSETOKEN")
if(key == null)
	key = 'dev'
curseforge {
  apiKey = key
  project {
    id = '535730'
    changelog = file('changelog.md')
    releaseType = 'release'
    changelogType = 'markdown'
    addGameVersion '1.21.8'
  }
}

version = ver
group = 'eu.gir'
base.archivesName = 'invisiblelights'

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        modSource project.sourceSets.main
    }
    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', 'invisiblelights'
    }
    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', 'invisiblelights'
        programArgument '--nogui'
    }
}

dependencies {
    implementation 'net.neoforged:neoforge:21.8.53'
}

jar {
    manifest {
        attributes([
            "Specification-Title": "invisiblelights",
            "Specification-Vendor": "German Immersive Railroading Community",
            "Specification-Version": ver,
            "Implementation-Title": project.name,
            "Implementation-Version": ver,
            "Implementation-Vendor" :"German Immersive Railroading Community",
            "Implementation-Timestamp": new Date().format("dd-MM-yyyy'T'HH:mm:ssZ")
        ])
    }
}

processResources {
    inputs.property "version", ver

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": ver
    }
}
