buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url "https://plugins.gradle.org/m2/" }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
        classpath "gradle.plugin.com.matthewprenger:CurseGradle:1.4.0"
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'eclipse'
apply plugin: 'maven-publish'

apply plugin: "com.matthewprenger.cursegradle"

repositories {
    mavenCentral()
    maven {
        name = 'Forge'
        url = 'https://maven.minecraftforge.net/'
    }
    maven {
        name = 'Mojang'
        url = 'https://libraries.minecraft.net/'
    }
}

def ver = System.getenv("APPVEYOR_BUILD_VERSION")
if(ver == null)
	ver = '0.0.0'

def key = System.getenv("CURSETOKEN")
if(key == null)
	key = 'dev'
curseforge {
  apiKey = key
  project {
    id = '535730'
    changelog = file('changelog.md')
    releaseType = 'release'
    changelogType = 'markdown'
    addGameVersion '1.18.1'
  }
}

version = ver
group = 'eu.gir'
archivesBaseName = 'invisiblelights'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.18.1'
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
            mods {
                invisiblelights {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
            mods {
                invisiblelights {
                    source sourceSets.main
                }
            }
        }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.18.1-39.1.2'
}

jar {
    manifest {
        attributes([
            "Specification-Title": "invisiblelights",
            "Specification-Vendor": "German Immersive Railroading Community",
            "Specification-Version": ver,
            "Implementation-Title": project.name,
            "Implementation-Version": ver,
            "Implementation-Vendor" :"German Immersive Railroading Community",
            "Implementation-Timestamp": new Date().format("dd-MM-yyyy'T'HH:mm:ssZ")
        ])
    }
}

processResources {
    inputs.property "version", ver

    filesMatching("META-INF/mods.toml") {
        expand "version": ver
    }
}

jar.finalizedBy('reobfJar')
