# Gradle settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Meta
mod_name=Invisible Lights
mod_group=com.troblecodings
mod_version=1.1.0

# Minecraft
minecraft_version=1.15.2

# Forge
forge_version=31.2.60
loader=forge

# Java
java_version=8

# Publishing
curseforge_project_id=535730
modrinth_project_id=vzwkaFP2
