modLoader="javafml"
loaderVersion="[39,)"
license="Apache-2.0"
issueTrackerURL="https://discord.gg/Va5P7KBry6"

[[mods]]
modId="invisiblelights"
version="${version}"
displayName="Invisible Lights"
authors="MrTroble, Jeronimo"
credits="German Immersive Railroading Community"
description='''
Adds invisible lights.
'''

[[dependencies.invisiblelights]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.invisiblelights]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"
