modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/MrTroble/InvisibleLights/issues"
license="Apache License Version 2.0"

[[mods]]
modId="invisiblelights"
version="${file.jarVersion}"
displayName="Invisible Lights"
displayURL="https://troblecodings.com/"
authors="MrTroble, Jeronimo, Luex"
credits="German Immersive Railroading Community"
description="Adds invisible lights."

[[dependencies.invisiblelights]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.invisiblelights]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
