modLoader="javafml"
loaderVersion="[5,)"
issueTrackerURL="https://github.com/MrTroble/InvisibleLights/issues"
license="Apache-2.0"

[[mods]]
modId="invisiblelights"
version="${file.jarVersion}"
displayName="Invisible Lights"
displayURL="https://troblecodings.com/"
authors="MrTroble, Jeronimo, Luex"
credits="German Immersive Railroading Community"
description="Adds invisible lights."

[[dependencies.invisiblelights]]
    modId="neoforge"
    type="required"
    versionRange="[21.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.invisiblelights]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.5]"
    ordering="NONE"
    side="BOTH"
