modLoader="javafml"
loaderVersion="[4,)"
license="Apache-2.0"
issueTrackerURL="https://discord.gg/Va5P7KBry6"

[[mods]]
modId="invisiblelights"
version="${version}"
displayName="Invisible Lights"
authors="MrTroble, Jeronimo"
credits="German Immersive Railroading Community"
description='''
Adds invisible lights.
'''

[[dependencies.invisiblelights]]
    modId="neoforge"
    type="required"
    versionRange="[21.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.invisiblelights]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="NONE"
    side="BOTH"
